"""Exact preset-managed runtime kernel inventory."""
from pathlib import Path

SKILL_RUNTIME_KERNEL_PATHS = (
    Path("__init__.py"),
    Path("bootstrap.py"),
    Path("command.py"),
    Path("compat.py"),
    Path("discovery.py"),
    Path("eval_runner.py"),
    Path("installed.py"),
    Path("io.py"),
    Path("lifecycle_helpers.py"),
    Path("launch.sh"),
    Path("probe.py"),
    Path("python-runtime.json"),
    Path("reviewed_content.py"),
    Path("qualification_facts.py"),
    Path("requirements.lock"),
    Path("resolve-python.sh"),
    Path("schema.py"),
    Path("temporary-inventory.json"),
    Path("temporary_lifecycle.py"),
    Path("validate.py"),
    Path("task_lifecycle/__init__.py"),
    Path("task_lifecycle/active_checkout.py"),
    Path("task_lifecycle/branch_resolution.py"),
    Path("task_lifecycle/branch_store.py"),
    Path("task_lifecycle/checkout_acquisition.py"),
    Path("task_lifecycle/checkout_resolution.py"),
    Path("task_lifecycle/closure_result.py"),
    Path("task_lifecycle/composition.py"),
    Path("task_lifecycle/errors.py"),
    Path("task_lifecycle/git_facts.py"),
    Path("task_lifecycle/handoff_cleanup.py"),
    Path("task_lifecycle/identity.py"),
    Path("task_lifecycle/rebind.py"),
    Path("task_lifecycle/resource_ledger.py"),
    Path("task_lifecycle/results.py"),
    Path("task_lifecycle/schema.py"),
    Path("task_lifecycle/session_adapter.py"),
    Path("task_lifecycle/source.py"),
)
