from __future__ import annotations
import hashlib,json,subprocess,sys,tempfile,unittest
from pathlib import Path
PACKAGE=Path(__file__).resolve().parents[1];SKILLS=PACKAGE.parents[1];LOCAL=PACKAGE/"runtime"
for p in (SKILLS,LOCAL):
 if str(p) not in sys.path:sys.path.insert(0,str(p))
from runtime.io import CommandError
import check,execute,invoke,record
class CommitTest(unittest.TestCase):
 def setUp(self):
  self.tmp=tempfile.TemporaryDirectory();self.repo=Path(self.tmp.name);subprocess.run(["git","init","-q","-b","feat/test",str(self.repo)],check=True);self.git("config","user.name","Test");self.git("config","user.email","test@example.invalid");(self.repo/"reviewed.txt").write_text("old\n");(self.repo/"unrelated.txt").write_text("old\n");td=self.repo/".trellis/tasks/08-12-test";td.mkdir(parents=True);(td/"task.json").write_text(json.dumps({"id":"08-12-test","status":"in_progress","branch":"feat/test","base_branch":"main"}));(td/"issue-scope-ledger.json").write_text(json.dumps({"primary_issue":{"number":1}}));self.git("add",".");self.git("commit","-qm","seed");self.head=self.git("rev-parse","HEAD");phase2=self.repo/".trellis/.runtime/guru-team/owner-checkpoints/08-12-test/phase2-check.json";phase2.parent.mkdir(parents=True);phase2.write_text(json.dumps({"typed_exit":"passed","task_ref":".trellis/tasks/08-12-test","phase2_capture_commit":self.head}));(self.repo/"reviewed.txt").write_text("new\n");(self.repo/"unrelated.txt").write_text("unrelated new\n");self.candidate=self.make_candidate()
 def tearDown(self):self.tmp.cleanup()
 def git(self,*a):return subprocess.run(["git",*a],cwd=self.repo,text=True,stdout=subprocess.PIPE,check=True).stdout.strip()
 def write(self,n,v):p=self.repo/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v));return p
 def entry(self,path):
  q=self.repo/path;blob=self.git("rev-parse",f"HEAD:{path}");return {"path":path,"index_status":" ","worktree_status":"M","untracked":False,"deleted":False,"renamed_from":None,"copied_from":None,"index_blob":blob,"worktree_sha256":hashlib.sha256(q.read_bytes()).hexdigest(),"mode":"100644"}
 def make_candidate(self):
  subject="feat(test): #1 add reviewed change";body="Background:\nTest exact commit behavior.\n\nChanges:\nCommit reviewed.txt only.\n\nBoundaries:\nPreserve unrelated changes.\n\nValidation:\nRun package tests.\n\nRefs #1";return {"$schema":"https://github.com/castbox/guru-trellis/schemas/guru-task-commit-candidate-5.0.json","schema_version":"5.0","skill_id":"guru-create-task-commit","sequence":"001","task":{"id":"08-12-test","path":".trellis/tasks/08-12-test","status":"in_progress","branch":"feat/test"},"git":{"base_branch":"main","base_ref":"HEAD^","pre_commit_head":self.head,"phase2_commit_anchor":self.head},"dirty_snapshot":{"entries":[self.entry("reviewed.txt"),self.entry("unrelated.txt")]},"path_classifications":[{"path":"reviewed.txt","category":"task-reviewed","reason":"Phase 2 reviewed this file.","coverage_source":"guru-check-task"},{"path":"unrelated.txt","category":"unrelated-preserved","reason":"Belongs to another change.","coverage_source":"current worktree"}],"exact_stage_paths":["reviewed.txt"],"message":{"type":"feat","scope":"test","summary":"add reviewed change","background":"Test exact commit behavior.","changes":"Commit reviewed.txt only.","boundaries":"Preserve unrelated changes.","validations":"Run package tests.","subject":subject,"body":body,"bytes":subject+"\n\n"+body+"\n"},"ai_review":{"status":"passed","summary":"Exact paths and message reviewed.","evidence":["Phase 2 covers reviewed.txt."]}}
 def test_real_isolated_exact_commit_and_dynamic_output(self):
  authoring={k:self.candidate[k] for k in ("path_classifications","message","ai_review")};public=self.write(".trellis/.runtime/guru-team/test-inputs/public.json",{"profile":"initial_commit","source_exit":"passed","mode":"workflow","task_ref":".trellis/tasks/08-12-test","phase2_commit_anchor":self.head});prepared=record.run(PACKAGE,{},["--root",str(self.repo),"--input",str(public),"--candidate-json",json.dumps(authoring)]);cp=self.repo/prepared["candidate_artifact"];self.assertEqual("committed",prepared["typed_exit"]);self.assertEqual("committed",check.run(PACKAGE,{},["--root",str(self.repo),"--candidate-artifact",str(cp)])["typed_exit"]);result=execute.run(PACKAGE,{},["--root",str(self.repo),"--candidate-artifact",str(cp)]);self.assertEqual("",self.git("diff","--cached","--name-only"));self.assertEqual("M unrelated.txt",self.git("status","--short","--untracked-files=no"));self.assertEqual("new",self.git("show","HEAD:reviewed.txt"));self.assertEqual("old",self.git("show","HEAD:unrelated.txt"));self.assertEqual("unrelated new",(self.repo/"unrelated.txt").read_text().strip());self.assertEqual("committed",result["exit"]);self.assertFalse(cp.exists())
 def test_snapshot_drift_rejected_before_commit(self):
  cp=self.write("candidate.json",self.candidate);(self.repo/"reviewed.txt").write_text("drift\n")
  with self.assertRaises(CommandError):execute.run(PACKAGE,{},["--root",str(self.repo),"--candidate-artifact",str(cp)])
  self.assertEqual(self.head,self.git("rev-parse","HEAD"))
 def test_rename_stages_reviewed_destination_and_source(self):
  self.git("mv","reviewed.txt","renamed.txt");self.candidate["dirty_snapshot"]["entries"]=[{"path":"reviewed.txt","index_status":" ","worktree_status":"D","untracked":False,"deleted":True,"renamed_from":None,"copied_from":None,"index_blob":self.git("rev-parse","HEAD:reviewed.txt"),"worktree_sha256":None,"mode":"100644"},{"path":"renamed.txt","index_status":" ","worktree_status":"?","untracked":True,"deleted":False,"renamed_from":"reviewed.txt","copied_from":None,"index_blob":None,"worktree_sha256":hashlib.sha256((self.repo/"renamed.txt").read_bytes()).hexdigest(),"mode":"100644"}];self.candidate["path_classifications"]=[{"path":"renamed.txt","category":"task-reviewed","reason":"Reviewed rename.","coverage_source":"guru-check-task"}];self.candidate["exact_stage_paths"]=["renamed.txt","reviewed.txt"];cp=self.write("rename.json",self.candidate);execute.run(PACKAGE,{},["--root",str(self.repo),"--candidate-artifact",str(cp)]);self.assertEqual("",self.git("ls-tree","--name-only","HEAD","reviewed.txt"));self.assertEqual("renamed.txt",self.git("ls-tree","--name-only","HEAD","renamed.txt"))
 def test_runtime_has_no_placeholder_or_example_projection(self):
  for p in LOCAL.glob("*.py"):
   t=p.read_text();self.assertNotIn("mutation is unavailable",t);self.assertNotIn("guru_team_trellis.py",t);self.assertNotIn("typed_output(package_root",t)
if __name__=="__main__":unittest.main()
